const API_CONFIG = {
  AUTH_SERVER: process.env.NEXT_PUBLIC_AUTH_SERVER_URL!,
  MARKET_SERVER: process.env.NEXT_PUBLIC_MARKET_SERVER_URL!,
  CALC_SERVER: process.env.NEXT_PUBLIC_CALC_SERVER_URL!,
  API_SERVER: process.env.NEXT_PUBLIC_API_SERVER_URL!,
};

export { API_CONFIG };
