const API_CONFIG = {
  AUTH_SERVER: process.env.NEXT_PUBLIC_AUTH_SERVER!,
  MARKET_SERVER: process.env.NEXT_PUBLIC_MARKET_SERVER!,
  CALC_SERVER: process.env.NEXT_PUBLIC_CALC_SERVER!,
  API_SERVER: process.env.NEXT_PUBLIC_API_SERVER!,
};

export { API_CONFIG };
